# Generated by Django 6.0.2 on 2026-02-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='max_capacity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='bin',
            constraint=models.CheckConstraint(
                check=models.Q(('current_capacity__gte', 0), ('current_capacity__lte', models.F('max_capacity'))),
                name='valid_bin_capacity'
            ),
        ),
    ]
