# Generated by Django 4.2.28 on 2026-03-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_bin_max_capacity_bin_valid_bin_capacity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bin',
            options={'ordering': ['shelf', 'position']},
        ),
        migrations.AddField(
            model_name='bin',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bin',
            name='rfid',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bin',
            name='shelf',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
