# Generated by Django 6.0.2 on 2026-02-27 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockmovement',
            old_name='produdct',
            new_name='product',
        ),
    ]
