# Generated by Django 6.0.2 on 2026-02-27 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_produdct_stockmovement_product'),
        ('warehouse', '0002_bin_max_capacity_bin_valid_bin_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='storage_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='warehouse.storagetype'),
        ),
    ]
