version: '3.9'

services:
  db:
    image: postgres:15
    container_name: warehouse_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    container_name: warehouse_app
    command: >
      sh -c "python manage.py migrate &&
             gunicorn warehouse_management.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}

  redis:
    image: redis:7
    container_name: warehouse_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: